import * as U from '../../utils/models'

export const Enum = U.strEnum([
  'eval',
  'inline-source-map',
  'cheap-eval-source-map',
  'cheap-source-map',
  'cheap-module-eval-source-map',
  'cheap-module-source-map',
  'eval-source-map',
  'source-map',
  'nosources-source-map',
  'hidden-source-map',
  'nosources-source-map',
  '@eval',
  '@inline-source-map',
  '@cheap-eval-source-map',
  '@cheap-source-map',
  '@cheap-module-eval-source-map',
  '@cheap-module-source-map',
  '@eval-source-map',
  '@source-map',
  '@nosources-source-map',
  '@hidden-source-map',
  '@nosources-source-map',
  '#eval',
  '#inline-source-map',
  '#cheap-eval-source-map',
  '#cheap-source-map',
  '#cheap-module-eval-source-map',
  '#cheap-module-source-map',
  '#eval-source-map',
  '#source-map',
  '#nosources-source-map',
  '#hidden-source-map',
  '#nosources-source-map',
  '#@eval',
  '#@inline-source-map',
  '#@cheap-eval-source-map',
  '#@cheap-source-map',
  '#@cheap-module-eval-source-map',
  '#@cheap-module-source-map',
  '#@eval-source-map',
  '#@source-map',
  '#@nosources-source-map',
  '#@hidden-source-map',
  '#@nosources-source-map',
])

export type Type = keyof typeof Enum | boolean
